<?php
  
  # loom-weaver.php @generated by Loom

  # psr-4 namespace autoloading

  require_once "loom/Psr4Autoloader.php";

  $universalNamespaces = array('Outsights' => 'outsights/Outsights');
  $psr4Autoloader = new Psr4Autoloader();
  $psr4Autoloader->register();

  foreach ($universalNamespaces as $namespace => $path) {
    $psr4Autoloader->addNamespace($namespace, $path);
  }
